version: '3'
services:
  virtuoso_mdb:
    image: openlink/virtuoso-opensource-7:7.2.6-r3-g1b16668
    container_name: virtuoso_mdb
    environment:
      DBA_PASSWORD: ${VIRTUOSO_DBA_PASSWORD}
      VIRT_Parameters_DirsAllowed: "., ../vad, /usr/share/proj, /database, /data"
      VIRT_Parameters_NumberOfBuffers: 170000
      VIRT_Parameters_MaxDirtyBuffers: 130000
      VIRT_Client_SQL_PREFETCH_ROWS: "10000"
      VIRT_Client_SQL_PREFETCH_BYTES: "160000"
      VIRT_SPARQL_ResultSetMaxRows: "1000000"
      VIRT_SPARQL_MaxSortedTopRows: "100000"
      VIRT_SPARQL_MaxQueryExecutionTime: "300"
      VIRT_SPARQL_MaxQueryCostEstimationTime: "-1"
    volumes:
      - /home/tf/project/rdf/data/rdf/mdb:/database
      - ./data:/data
    ports:
      - "8891:8890"
    networks:
      - togodx-tpp
    user: ${UID:-0}:${GID:-0}
  virtuoso_sc:
    image: openlink/virtuoso-opensource-7:7.2.6-r3-g1b16668
    container_name: virtuoso_sc
    environment:
      DBA_PASSWORD: ${VIRTUOSO_DBA_PASSWORD}
      VIRT_Parameters_DirsAllowed: "., ../vad, /usr/share/proj, /database, /data"
      VIRT_Parameters_NumberOfBuffers: 170000
      VIRT_Parameters_MaxDirtyBuffers: 130000
      VIRT_Client_SQL_PREFETCH_ROWS: "10000"
      VIRT_Client_SQL_PREFETCH_BYTES: "160000"
      VIRT_SPARQL_ResultSetMaxRows: "1000000"
      VIRT_SPARQL_MaxSortedTopRows: "100000"
      VIRT_SPARQL_MaxQueryExecutionTime: "300"
      VIRT_SPARQL_MaxQueryCostEstimationTime: "-1"
    volumes:
      - /home/tf/project/rdf/data/rdf/sc/:/database
      - ./data:/data
    ports:
      - "8892:8890"
    networks:
      - togodx-tpp
    user: ${UID:-0}:${GID:-0}
  virtuoso_nbdc_pubchem:
    image: openlink/virtuoso-opensource-7:7.2.6-r3-g1b16668
    container_name: virtuoso_nbdc_pubchem
    environment:
      DBA_PASSWORD: ${VIRTUOSO_DBA_PASSWORD}
      VIRT_Parameters_DirsAllowed: "., ../vad, /usr/share/proj, /database, /data"
      VIRT_Parameters_NumberOfBuffers: 170000
      VIRT_Parameters_MaxDirtyBuffers: 130000
      VIRT_Client_SQL_PREFETCH_ROWS: "10000"
      VIRT_Client_SQL_PREFETCH_BYTES: "160000"
      VIRT_SPARQL_ResultSetMaxRows: "1000000"
      VIRT_SPARQL_MaxSortedTopRows: "100000"
      VIRT_SPARQL_MaxQueryExecutionTime: "300"
      VIRT_SPARQL_MaxQueryCostEstimationTime: "-1"
    volumes:
      - /home/tf/project/rdf/data/rdf/pubchem/20220226:/database
      - ./data:/data
    ports:
      - "8894:8890"
    networks:
      - togodx-tpp
    user: ${UID:-0}:${GID:-0}
  virtuoso_nbdc_primary:
    image: openlink/virtuoso-opensource-7:7.2.6-r3-g1b16668
    container_name: virtuoso_nbdc_primary
    environment:
      DBA_PASSWORD: ${VIRTUOSO_DBA_PASSWORD}
      VIRT_Parameters_DirsAllowed: "., ../vad, /usr/share/proj, /database, /data"
      VIRT_Parameters_NumberOfBuffers: 170000
      VIRT_Parameters_MaxDirtyBuffers: 130000
      VIRT_Client_SQL_PREFETCH_ROWS: "10000"
      VIRT_Client_SQL_PREFETCH_BYTES: "160000"
      VIRT_SPARQL_ResultSetMaxRows: "1000000"
      VIRT_SPARQL_MaxSortedTopRows: "100000"
      VIRT_SPARQL_MaxQueryExecutionTime: "300"
      VIRT_SPARQL_MaxQueryCostEstimationTime: "-1"
    volumes:
      - /home/tf/project/rdf/data/rdf/primary/20220308:/database
      - ./data:/data
    ports:
      - "8893:8890"
    networks:
      - togodx-tpp
networks:
  togodx-tpp:
    external:
      name: togodx-tpp
